
export const Menu=[{
    deptId:1,
    deptName:"ENT",
    doctorId:1,
    doctorName:"name1",
    slotAvailability:{
      startTime:9,
      stopTime:18,
      interval:15
    }
  },
  {
    deptId:2,
    deptName:"Dermatology",
    doctorId:2,
    doctorName:"name2",
    slotAvailability:{
      startTime:3,
      stopTime:20,
      interval:20
    }
  },
  {
    deptId:1,
    deptName:"ENT",
    doctorId:3,
    doctorName:"name3",
    slotAvailability:{
      startTime:3,
      stopTime:20,
      interval:15
    }
  },
  {
    deptId:3,
    deptName:"Physical",
    doctorId:4,
    doctorName:"name4",
    slotAvailability:{
      startTime:9,
      stopTime:18,
      interval:15
    }
  }]